Drop Table Vendor;
Drop Table Items;

Create table Vendors
VendorID NUMBER(5),
Vendor_Name VARCHAR(40) CONSTRAINT VN_NN NOT NULL,
Vendor_Email VARCHAR(40) CONSTRAINT VE_NN NOT NULL,
Vendor_Phone Number(9) CONSTRAINT VP_NN NOT NULL,
CONSTRAINT VendorID_PK PRIMARY KEY (VendorID));

Create table Items
ItemID NUMBER(8),
VendorID NUMBER(5),
Name VARCHAR(30) CONSTRAINT NAME_NN NOT NULL,
Price NUMBER(4,2) CONSTRAINT PRICE_NN NOT NULL,
Quantity NUMBER(3) CONSTRAINT QUANTITY_NN NOT NULL,
Category VARCHAR(20) CONSTRAINT CATEGORY_NN NOT NULL,
CONSTRAINT ItemID_PK PRIMARY KEY (ItemID),
CONSTRAINT VendorID_FK FOREIGN KEY (VendorID) REFERENCES VENDORS (VendorID));
