Drop Table Items;

Create table Items
ItemID NUMBER(8),
VendorID NUMBER(5),
Name VARCHAR(30) CONSTRAINT NAME_NN NOT NULL,
Price NUMBER(4,2) CONSTAINT PRICE_NN NOT NULL,
Quantity NUMBER(3) CONSTRAINT QUANTITY_NN NOT NULL,
Category VARCHAR(20) CONSTRAINT CATEGORY_NN NOT NULL,
CONSTRAINT ItemID_PK PRIMARY KEY (ItemID));
